### PR TITLE
Fix bashisms

### PR DESCRIPTION
**Pull request by AMDmi3**
- Use [ instead of [[
- Use read instead of arrays
- Don't use `exit -1` (unportable)
- Switch to /bin/sh shebangs
- Output error messages to stderr instead of stdout

This may require additional testing, I haven't tested all commands

### CODE REVIEW

**Comment by da-x** [comment]
Thanks. On what platforms `bash` is missing, BTW?

**Comment by AMDmi3** [comment]
FreeBSD, likely other BSD's

**Comment by da-x** [comment]
But `bash` can be provided with Ports on these platforms, no?

**Comment by AMDmi3** [comment]
Yes, but it's not available by default and is never available as `/bin/bash` (`/usr/local/bin/bash` instead).

**Comment by da-x** [comment]
I see. Provided that `bash` is installed, would `#!/usr/bin/env bash` work there instead of `#!/bin/bash`?

**Comment by AMDmi3** [comment]
Yes, but I still strongly advise against keeping dependency on bash, it's totally unneeded here.

**Comment by da-x** [comment]
Given the preponderance of `bash` nowadays on UNIX's (and even Windows), I ought to disagree. I do like the changes regarding the `stderr` redirection - so maybe we can keep that, along with the change to `#!/usr/bin/env bash`, if you amend your pull request. Thanks!

**Comment by AMDmi3** [comment]
Preponderance lacks any guarantees, while /bin/sh is actually available on any *nix system (be it a link on bash or a separate POSIX compatible shell). The point of this PR is to make your scripts more portable, and it comes at zero price, e.g. without any code complication or performance degradation, cause you don't really need any bash specific features. There's no point in this change without dropping bash requirement.

**Comment by da-x** [comment]
The price is not zero - I prefer the `bash` syntax of `sh` and rather not regress to `sh` for that matter. So, features or portability are not the only consideration there.

**Comment by AMDmi3** [comment]
Then I have no interest in non-portable project, sorry.

**Pull request closed without merging**
